---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glaa-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glaa-web
    spec:  
      containers:
      - name: glaa-web
        securityContext:
          runAsNonRoot: true            
        image: quay.io/ukhomeofficedigital/glaa-web:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: password
          - name: APP_USER
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: username
          - name: APP_PASS
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: password
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
        volumeMounts:
          - name: secrets
            mountPath: /home/app/glaa-web/secrets/
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
          items:
          - key: appsettings.secrets.json
            path: appsettings.secrets.json