---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glaa-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: glaa-web
    spec:
      containers:
      - name: glaa-web
        securityContext:
          runAsNonRoot: true
        image: quay.io/ukhomeofficedigital/glaa-web:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: password
          - name: APP_USER
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: username
          - name: APP_PASS
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: password
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SuperUser
            valueFrom:
              secretKeyRef:
                name: glaa-app-secrets
                key: su
          - name: GOVNotify
            valueFrom:
              secretKeyRef:
                name: glaa-app-secrets
                key: notify
          - name: DefaultStatuses
            valueFrom:
              secretKeyRef:
                name: glaa-app-secrets
                key: statuses
                key: password
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-glaa-notprod
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-glaa-notprod
                key: secret_access_key