---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: glaa-web-network-policy-external
  namespace: glaa-dev
spec:
  podSelector:
    matchLabels:
      {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
        - protocol: TCP
          port: 5000