---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: glaa-web-ingress-network-policy
spec:
  podSelector:
    matchLabels:
      app: glaa-web
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-internal
      ports:
        - protocol: TCP
          port: 80