---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glaa-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: glaa-db
    spec:  
      containers:
      - name: glaa-db
        securityContext:
          runAsNonRoot: true            
        image: quay.io/ukhomeofficedigital/glaa-db:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: endpoint   
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: port                         
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: username          
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: password                              