---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glaa-db-setup
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: glaa-db-setup
    spec:  
      containers:
      - name: glaa-db-setup
        securityContext:
          runAsNonRoot: true            
        image: quay.io/ukhomeofficedigital/glaa-db-setup:v0_1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: endpoint
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: port
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: glaadev-rds-access
                key: password
          - name: APP_USER
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: username
          - name: APP_PASS
            valueFrom:
              secretKeyRef:
                name: glaa-db-app-user
                key: password